# Generated by Django 3.1.5 on 2021-01-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullscreen', models.IntegerField(default=0)),
                ('multiperson', models.IntegerField(default=0)),
                ('audio', models.IntegerField(default=0)),
                ('facedir', models.IntegerField(default=0)),
                ('facesim', models.IntegerField(default=0)),
                ('othergadgets', models.IntegerField(default=0)),
            ],
        ),
    ]
