# Generated by Django 3.1.5 on 2021-01-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='screenfocus',
            field=models.IntegerField(default=0),
        ),
    ]
