# Generated by Django 3.1.5 on 2021-02-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0002_violation_screenfocus'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
