# Generated by Django 3.1.5 on 2021-02-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0003_violation_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='thumb',
        ),
    ]
