# Generated by Django 3.1.5 on 2021-02-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
